# Generated by Django 2.2.2 on 2019-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_2', models.IntegerField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('reacts', models.IntegerField(max_length=10)),
            ],
        ),
    ]
