# Generated by Django 2.2.2 on 2019-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='question',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
