# Generated by Django 2.2.2 on 2019-10-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_1',
            field=models.CharField(max_length=100),
        ),
    ]
